### ISSUE TITLE
Spelling in README.md

### ISSUE THREAD

**Issue by teacher4711** [portapps/intellij-idea-ultimate-portable#1]
Please don't be angry with me for hinting at these typos:

You could capitalize the 'i' in "How can i help ?"
You could change "welcomed" to "welcome".

Thanks for the great work!
Is there a way to build the files on my own? If yes and in case it is not too complicated, could you write a little guide in the README.md?

Cheers
Mike

**Comment by crazy-max** [comment]
Hi @teacher4711, thanks for the typos ;)
Regarding how to build a portable release of intellij, I have to write a small guide for this like you said. I keep you in touch ;)

**Comment by teacher4711** [comment]
Thanks, but don't feel obliged to. You're doing a great job and you're super fast!
