### ISSUE TITLE
Wrong parameter passed to idea64.exe

### ISSUE THREAD

**Issue by 0x7FFFFFFFFFFFFFFF** [portapps/intellij-idea-ultimate-portable#10]
#### Steps to reproduce this issue

1. Add portable IDEA folder to the PATH environment variable. On my machine, it's `C:\portapps\intellij-idea-ultimate-portable`
2. Create a folder `C:\my_projects\idea_test`
3. Open a command line window, navigate to `C:\my_projects\idea_test` and run `intellij-idea-ultimate-portable.exe .`

#### Expected behaviour

IDEA should open the folder `C:\my_projects\idea_test` as a project and this is exactly the native idea64.exe's behavior.

#### Actual behaviour

The folder `C:\portapps\intellij-idea-ultimate-portable\app\bin` was opened as a project in IDEA.

### Configuration

**App release / arch (ex. 1.0.0-2 win64)** :
IntelliJ IDEA Ultimate 2019.3.1
Portapps 1.31.0

**Operating system (ex. Windows 10 Pro 64 bits)** :
Windows 10 Pro 64 bits

**Winver screenshot** :
![image](https://user-images.githubusercontent.com/39968/72603159-78cd2300-3953-11ea-94d1-b421727a850c.png)

### Screenshots

> If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/39968/72603358-cfd2f800-3953-11ea-8523-19758719e09b.png)

**Comment by crazy-max** [comment]
@yangshuairocks I will take a look on this. Thanks for your input.

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
https://github.com/portapps/portapps/issues/122




I did some test and found that it's the idea64.exe can't correctly handle `.` as parameter. When you pass a directory to it like `idea64 my_app`, it can open the folder correctly, but it can't handle `idea64 .`. The corresponding code is

https://github.com/portapps/intellij-idea-ultimate-portable/blob/c08d4ac36c218841b78ae50d40188c740877e9da/main.go#L68

We'd better check if there are only two arguments (the executable and a directory name or file name). If so, we convert the path to absolute.
```go
	if len(os.Args) == 2 {
		os.Args[1], _ = filepath.Abs(os.Args[1])
	}
```

From IDEA's document https://www.jetbrains.com/help/idea/working-with-the-ide-features-from-command-line.html, there is only a single one-parameter case, which is opening a file or folder. So this shouldn't introduce any parameter issues.

| Argument | Description |
-- | --
Path to file or directory | Open the file or directory specified as the argument.  For more information, see Open files from the command line.

**Comment by crazy-max** [comment]
Should be fixed since latest release
