### ISSUE TITLE
build it locally

### ISSUE THREAD

**Issue by zirconias** [portapps/intellij-idea-ultimate-portable#11]
i would like to download it, but i'm behind a proxy which prevents me doing it.

i'm wondering if i can build it myself, or at least rename the .exe

non applicable.
#### Steps to reproduce this issue

1.
2.
3.

#### Expected behaviour

> Tell me what should happen

#### Actual behaviour

> Tell me what happens instead

### Configuration

**App release / arch (ex. 1.0.0-2 win64)** :

**Operating system (ex. Windows 10 Pro 64 bits)** :

**Winver screenshot** :

> Open a command prompt and type winver then take / save the screenshot of the window and drag the image file in this issue. For example: http://bit.ly/2vA5sxR

### Screenshots

> If applicable, add screenshots to help explain your problem.

### Logs

Join the log file `log\[appname]-portable.log` to this issue.

**Comment by crazy-max** [comment]
You can build it locally by following these instructions: https://portapps.io/doc/contribute/
