### ISSUE TITLE
Wrong parameter in installer

### ISSUE THREAD

**Issue by realkot** [portapps/intellij-idea-ultimate-portable#14]
#### Steps to reproduce this issue

1. Get the latest intellij-idea-ultimate-portable-2020.1.1-25-setup.exe
2. Install as usual (for me d:\portapps\IntelliJ IDEA Ultimate Portable\ )
3. Set the launch the programm checkbox to "true"
![изображение](https://user-images.githubusercontent.com/24507273/81712722-9df31d80-947d-11ea-9f1d-4a990d7740b5.png)

#### Expected behaviour

x64/x32 IDEA is launched

#### Actual behaviour

> The error:
![изображение](https://user-images.githubusercontent.com/24507273/81712495-54a2ce00-947d-11ea-9480-a762a0e4300f.png)

### Configuration

Windows 10 LTSC x64

**Winver screenshot** :

![изображение](https://user-images.githubusercontent.com/24507273/81713027-05a96880-947e-11ea-9ba0-ab8afeb5c8db.png)

**Comment by crazy-max** [comment]
@realkot Indeed, the wrapper is cut in 2 executables to satisfy the architecture.

**Comment by crazy-max** [comment]
Fixed
