### ISSUE TITLE
idea64.exe.vmoptions created in C:\Users\%USERNAME%\.IntelliJIdea2019.1\config\, not portable

### ISSUE THREAD

**Issue by yetangye** [portapps/intellij-idea-ultimate-portable#3]
#### Steps to reproduce this issue

1. Click IDEA Help-> Edit Custom VM Options... menu

#### Expected behaviour

> Tell me what should happen

Hope idea64.exe.vmoptions will be created in somewhere of portable IDEA folder.

#### Actual behaviour

> Tell me what happens instead

idea64.exe.vmoptions created in C:\Users\%USERNAME%\.IntelliJIdea2019.1\config\

### Configuration

**App release / arch (ex. 1.0.0-2 win64)** :

2019.1.3-7 Win64 (intellij-idea-ultimate-portable-2019.1.3-7-setup.exe)

**Operating system (ex. Windows 10 Pro 64 bits)** :

Windows 10 Enterprise, 64 bit

**Winver screenshot** :

> Open a command prompt and type winver then take / save the screenshot of the window and drag the image file in this issue. For example: http://bit.ly/2vA5sxR

### Screenshots

> If applicable, add screenshots to help explain your problem.

### Logs

Join the log file `log\[appname]-portable.log` to this issue.

**Comment by crazy-max** [comment]
Hi @yetangye,

I noticed this bug not long ago (since 2019.1 I think) and I had started working on it.
Now that someone has noticed this bug, I'll get back to it :innocent:

**Comment by yetangye** [comment]
Wow, What a nice man 😄 

> Hi @yetangye,
> 
> I noticed this bug not long ago (since 2019.1 I think) and I had started working on it.
> Now that someone has noticed this bug, I'll get back to it 😇

**Comment by crazy-max** [comment]
@yetangye Ok after digging it seems those paths [are hardcoded](https://github.com/JetBrains/intellij-community/blob/master/platform/util/src/com/intellij/openapi/application/PathManager.java#L591) to the user home unfortunately :slightly_frowning_face:. This applies to `Help > Edit Custom Properties...` and `Help > Edit Custom VM Options...`.

I believe JetBrains has implemented this behavior to allow each user of the same machine to customize these settings.
It is true that for a portable version it is useless and that is why I will allow to overload the VM options via a common configuration file in data (`data/idea.vmoptions`).

Maybe @trespasserw can highlight us about this :slightly_smiling_face:

**Comment by yetangye** [comment]
@crazy-max Thanks 😄 
`data/idea.vmoptions` will be a ideal location as you think.

I will try to advice to JetBrains.

> @yetangye Ok after digging it seems those paths [are hardcoded](https://github.com/JetBrains/intellij-community/blob/master/platform/util/src/com/intellij/openapi/application/PathManager.java#L591) to the user home unfortunately 🙁. This applies to `Help > Edit Custom Properties...` and `Help > Edit Custom VM Options...`.
> 
> I believe JetBrains has implemented this behavior to allow each user of the same machine to customize these settings.
> It is true that for a portable version it is useless and that is why I will allow to overload the VM options via a common configuration file in data (`data/idea.vmoptions`).
> 
> Maybe @trespasserw can highlight us about this 🙂

**Comment by crazy-max** [comment]
@yetangye Done. See https://portapps.io/app/intellij-idea-ultimate-portable/#infos

**Comment by trespasserw** [comment]
@crazy-max the *.vmoptions files are loaded by OS-specific launchers (*.exe, *.sh etc.) from a small number of predefined locations. Modifying files inside the installation isn't particularly good idea; I'd better use [the Toolbox scheme](https://github.com/JetBrains/intellij-community/blob/586932a06880926ca5049f42d84cbedb0eed7376/platform/build-scripts/resources/linux/scripts/executable-template.sh#L165).

**Comment by yetangye** [comment]
@crazy-max @trespasserw 

I just tested with version 2019.1.3-8, 

- Copy the options I'm using from C:\Users\whoami\.IntelliJIdea2019.1\config\idea64.exe.vmoptions to C:\some\where\intellij-idea-ultimate-portable\data\idea.vmoptions

- Delete folder C:\Users\whoami\.IntelliJIdea2019.1\

- Launch IDEA

It works. Thanks you very much!

> @yetangye Done. See https://portapps.io/app/intellij-idea-ultimate-portable/#infos
