### ISSUE TITLE
The 32bit support

### ISSUE THREAD

**Issue by zjzdy** [portapps/intellij-idea-ultimate-portable#4]
In intellij-idea-ultimate-portable-2019.2-9, not support 32bit.
The included JBR11 are x86-64 version, but JBR8 is x86 version.So, the Idea 2019.2 for Windows with Bundled JBR 8 support 32bit.(Url is https://download.jetbrains.com/idea/ideaIU-2019.2-jbr8.win.zip)
Please consider add a version use JBR8 for 2019.2. 
(Other Hit: idea has 2019.1.4 version, it default use JBR8, support 32bit)

**Comment by zjzdy** [comment]
Maybe change the program, has 2 app folder, a JBR11 version, a JBR8 version. The intellij-idea-ultimate-portable-win32 always run JBR8 version, and the intellij-idea-ultimate-portable-win64 provide JBR11/JBR8 version.

**Comment by crazy-max** [comment]
Hi @zjzdy,

Thanks, I wasn't aware of this change. I keep you in touch.

**Comment by zjzdy** [comment]
Additional Information:
I use the UltraCompare to binary diff the 2019.2's JBR11 and JBR8 version.
I find only has 3  folder different.
1. In /bin, the JBR8 version add the /bin/idea.exe and /bin/idea.exe.vmoptions.
2. JBR8 version add /jre32 folder.
3. /jbr folder.

![The UltraCompare screenshot](https://user-images.githubusercontent.com/10596496/62344814-270a1b00-b522-11e9-8625-a6b77ae2ba48.PNG)

Maybe can try https://www.jetbrains.com/help/idea/switching-boot-jdk.html in this.(Use JBR8 version to main version, because it has idea.exe)
And the StandAlone JetBrains Runtime can find in https://confluence.jetbrains.com/display/JBR/JetBrains+Runtime

It's up to you!

**Comment by crazy-max** [comment]
@zjzdy Should be ok with latest release : https://portapps.io/app/intellij-idea-ultimate-portable/#download
