### ISSUE TITLE
Will the plugin I installed remains after an update of portable IDEA?

### ISSUE THREAD

**Issue by yangshuairocks** [portapps/intellij-idea-ultimate-portable#9]
I came across this project today. I have some questions regarding the update of it. They are not on the FAQ or description of the project. 

1. I have installed Intellij IDEA through the Intellij Toolbox and have installed some plugins. Is it possible to move these plugins to the portable IDEA?
2. When I install plugins in the portable IDEA, will them remains the same after a later update?

Thanks.

**Comment by crazy-max** [comment]
@yangshuairocks 

> I have installed Intellij IDEA through the Intellij Toolbox and have installed some plugins. Is it possible to move these plugins to the portable IDEA?

Yes, migration step to move files is explained [here](https://portapps.io/app/intellij-idea-ultimate-portable/#installation).

> When I install plugins in the portable IDEA, will them remains the same after a later update?

Yes, everything kept in `data` folder is untouched.
